# Generated by Django 4.2.5 on 2023-10-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='govt_sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('documents', models.FileField(upload_to='upload/')),
                ('photo', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
